name: Alfresco Discord Bot

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.37.0
      - name: "Build and Test"
        env:
          ALFRESCO_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: ./mvnw -B -V install

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build Docker Image
        uses: docker/build-push-action@v4.0.0
        with:
          push: false
          tags: alfresco/alfresco-discord-bot:latest
      - name: "Run container"
        id: run-container
        env:
          ALFRESCO_BOT_TOKEN: ${{ secrets.DISCORD_BOT_TOKEN }}
        run: echo "CID=$(docker run --rm -d -e ALFRESCO_BOT_TOKEN=$ALFRESCO_BOT_TOKEN alfresco/alfresco-discord-bot:latest)" >> "$GITHUB_OUTPUT"
      - name: Wait a little for the startup to complete
        run: sleep 10
      - name: Inspect running state
        run: docker inspect ${{ steps.run-container.outputs.CID }} | jq -e '.[0].State.Running'
      - name: Print logs on failure
        if: failure()
        run: docker logs ${{ steps.run-container.outputs.CID }}
