name: Alfresco Discord Bot

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build_and_release:
    name: "Build and Release"
    uses: Alfresco/alfresco-build-tools/.github/workflows/build-and-release-maven.yml@v1.36.0
    secrets: inherit
